baseurl: /
title: Automatic Code Generation for Programming Tasks
subtitle: Documentation
author: Alexandru Dinu
simple_search: http://google.com/search
description: Notes and documentation
name: code-gen
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
post:
  template: _post.txt
  extension: md
page:
  template: _page.txt
  extension: md
git:
  branch: master
